version: '3'
services:
  mongo:
    image: "mongo:bionic"
    ports:
      - "27017:27017"
  web:
    network_mode: "host"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"