name: CI

on:
  pull_request:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: PR Checkout
    steps:
    - uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '12'
    - run: npm install -g yarn@1
    - run: |
        yarn install
        yarn test
      
      
